// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cgk.judgeit.domain;

import com.cgk.judgeit.domain.Image;
import javax.persistence.Entity;

privileged aspect Image_Roo_Jpa_Entity {
    
    declare @type: Image: @Entity;
    
}
