// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cgk.judgeit.domain;

import com.cgk.judgeit.domain.Image;

privileged aspect Image_Roo_JavaBean {
    
    public String Image.getLink() {
        return this.link;
    }
    
    public void Image.setLink(String link) {
        this.link = link;
    }
    
}
