// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cgk.judgeit.domain;

import com.cgk.judgeit.domain.Opinion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Opinion_Roo_Configurable {
    
    declare @type: Opinion: @Configurable;
    
}
