// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cgk.judgeit.domain;

import com.cgk.judgeit.domain.Rank;

privileged aspect Rank_Roo_JavaBean {
    
    public String Rank.getName() {
        return this.name;
    }
    
    public void Rank.setName(String name) {
        this.name = name;
    }
    
}
