// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cgk.judgeit.domain;

import com.cgk.judgeit.domain.Video;

privileged aspect Video_Roo_JavaBean {
    
    public String Video.getLink() {
        return this.link;
    }
    
    public void Video.setLink(String link) {
        this.link = link;
    }
    
}
